# Generated by Django 5.2.7 on 2026-05-21 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomilieNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homilinotes', to=settings.AUTH_USER_MODEL)),
                ('passage_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homilinote_ends', to='bible.verse')),
                ('passage_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homilinote_starts', to='bible.verse')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_homilinotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Note d'homélie",
                'verbose_name_plural': "Notes d'homélie",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de lecture',
                'verbose_name_plural': 'Plans de lecture',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlanPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_passages', to='bible.readingplan')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_passages', to='bible.verse')),
            ],
            options={
                'verbose_name': 'Passage du plan',
                'verbose_name_plural': 'Passages du plan',
                'ordering': ['day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LectioDivinaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lectio', models.TextField(blank=True)),
                ('meditatio', models.TextField(blank=True)),
                ('oratio', models.TextField(blank=True)),
                ('contemplatio', models.TextField(blank=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectio_sessions', to='bible.verse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectio_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Lectio Divina',
                'verbose_name_plural': 'Sessions Lectio Divina',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'passage')},
            },
        ),
    ]
