# Generated by Django 5.2.7 on 2026-06-05 15:26

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_add_pg_trgm_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verse',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_verse_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
