# Generated by Django 5.2.7 on 2026-07-19 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_verse_idx_verse_embedding_hnsw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscription à un parcours',
                'verbose_name_plural': 'Inscriptions aux parcours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lectiodivinasession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lectiodivinasession',
            name='session_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='lectiodivinasession',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectio_sessions', to='bible.verse'),
        ),
        migrations.AddConstraint(
            model_name='lectiodivinasession',
            constraint=models.UniqueConstraint(condition=models.Q(('passage__isnull', False)), fields=('user', 'passage'), name='uniq_lectio_user_passage'),
        ),
        migrations.AddConstraint(
            model_name='lectiodivinasession',
            constraint=models.UniqueConstraint(condition=models.Q(('passage__isnull', True)), fields=('user', 'session_date'), name='uniq_lectio_user_day_without_passage'),
        ),
        migrations.AddField(
            model_name='readingplansubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='bible.readingplan'),
        ),
        migrations.AddField(
            model_name='readingplansubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plan_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='readingplansubscription',
            constraint=models.UniqueConstraint(fields=('user', 'plan'), name='uniq_reading_plan_subscription'),
        ),
    ]
