# Generated by Django 5.2.7 on 2026-05-21 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention_type', models.CharField(choices=[('for_deceased', 'Pour un défunt'), ('for_living', 'Pour un vivant'), ('for_occasion', 'Pour une occasion'), ('for_community', 'Pour la communauté')], max_length=30)),
                ('intention_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('date_proposed', 'Date proposée'), ('confirmed', 'Confirmée'), ('celebrated', 'Célébrée'), ('declined', 'Refusée')], db_index=True, default='pending', max_length=20)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('celebration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_intentions', to='org.parish')),
                ('pretre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_intentions', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_intentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
