# Generated by Django 5.2.7 on 2026-05-21 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('donation_type', models.CharField(choices=[('sunday_collection', 'Quête du dimanche'), ('church_tithe', "Denier de l'Église"), ('mass_intention_offering', 'Offrande de messe'), ('special_project', 'Projet spécial'), ('free_donation', 'Don libre')], max_length=40)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('scope_type', models.CharField(default='global', max_length=20)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('payment_provider', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('cash', 'Espèces')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
