# Generated by Django 5.2.7 on 2026-05-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('org', '0003_backfill_main_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='org.parish'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_campaigns', to='org.church'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_campaigns', to='org.parish'),
        ),
    ]
