# Generated by Django 5.2.7 on 2026-06-01 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_anonymous_name(apps, schema_editor):
    """DÉFENSIF : avant le CHECK XOR, mettre en conformité les dons existants —
    un don sans donateur (donor NULL) reçoit un nom anonyme par défaut, et un don
    attribué (donor renseigné) voit son nom anonyme vidé."""
    Donation = apps.get_model("donations", "Donation")
    Donation.objects.filter(donor__isnull=True, anonymous_donor_name="").update(
        anonymous_donor_name="Anonyme"
    )
    Donation.objects.filter(donor__isnull=False).exclude(anonymous_donor_name="").update(
        anonymous_donor_name="", anonymous_donor_phone=""
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_backfill_donation_parish'),
        ('org', '0003_backfill_main_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='anonymous_donor_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='anonymous_donor_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='org.church'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué'), ('canceled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_anonymous_name, noop_reverse),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', False), ('anonymous_donor_name', '')), models.Q(('donor__isnull', True), models.Q(('anonymous_donor_name', ''), _negated=True)), _connector='OR'), name='donation_donor_xor_anonymous'),
        ),
    ]
