# Generated by Django 5.2.7 on 2026-05-21 17:38

import apps.messaging.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClergicalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_scope', models.CharField(choices=[('individual', 'Individuel'), ('parish_clergy', 'Clergé de la paroisse'), ('diocese_clergy', 'Clergé du diocèse'), ('province_bishops', 'Évêques de la province')], db_index=True, default='individual', max_length=20, verbose_name='portée')),
                ('scope_id', models.IntegerField(blank=True, help_text='ID de la paroisse, du diocèse ou de la province selon recipient_scope.', null=True, verbose_name='ID de la portée')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('body', apps.messaging.fields.EncryptedTextField(verbose_name='corps')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('individual_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_clerical_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_clerical_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message inter-clergé',
                'verbose_name_plural': 'Messages inter-clergé',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['individual_recipient', '-created_at'], name='clerical_msg_rcpt_idx'), models.Index(fields=['sender', '-created_at'], name='clerical_msg_sender_idx')],
            },
        ),
    ]
