# Generated by Django 5.2.7 on 2026-04-30 00:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Icône')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='Couleur hex')),
                ('display_order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'article",
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, default='', max_length=400, verbose_name='Résumé court')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('scope_type', models.CharField(choices=[('global', "Global (toute l'Église du Sénégal)"), ('diocese', 'Diocèse'), ('parish', 'Paroisse')], db_index=True, default='global', max_length=20, verbose_name='Portée')),
                ('scope_parish_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID paroisse (placeholder)')),
                ('scope_diocese_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID diocèse (placeholder)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('unpublished', 'Dépublié')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('unpublished_at', models.DateTimeField(blank=True, null=True, verbose_name='Dépublié le')),
                ('unpublish_reason', models.TextField(blank=True, default='', verbose_name='Motif de dépublication')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='files.file', verbose_name='Image de couverture')),
                ('unpublished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unpublished_articles', to=settings.AUTH_USER_MODEL, verbose_name='Dépublié par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.articlecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='article_status_pub_idx'), models.Index(fields=['scope_type', 'scope_parish_id', 'status'], name='article_parish_idx'), models.Index(fields=['scope_type', 'scope_diocese_id', 'status'], name='article_diocese_idx'), models.Index(fields=['category', 'status'], name='article_category_idx'), models.Index(fields=['author', '-created_at'], name='article_author_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'scope_type', 'scope_parish_id'), name='unique_article_slug_parish')],
            },
        ),
    ]
