# Generated by Django 5.2.7 on 2026-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('announcement', 'Annonce'), ('article', 'Article'), ('pastoral_letter', 'Lettre Pastorale')], db_index=True, default='article', max_length=20, verbose_name='Type de contenu'),
        ),
    ]
