# Generated by Django 5.2.7 on 2026-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_scope_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='announcement_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="Date de l'annonce"),
        ),
        migrations.AddField(
            model_name='article',
            name='content_format',
            field=models.CharField(choices=[('text', 'Texte brut'), ('html', 'HTML riche')], default='text', max_length=10, verbose_name='Format du contenu'),
        ),
    ]
