# Generated by Django 5.2.7 on 2026-07-19 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_backfill_content_format_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('pray', 'Je prie'), ('amen', 'Amen'), ('attend', 'Je participe')], db_index=True, max_length=20, verbose_name='Type de réaction')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.article', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réaction à un article',
                'verbose_name_plural': 'Réactions aux articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'reaction_type'], name='article_reaction_count_idx'), models.Index(fields=['user', 'article'], name='article_reaction_mine_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'user', 'reaction_type'), name='unique_article_reaction_per_user_and_type')],
            },
        ),
    ]
