# Generated by Django 5.2.7 on 2026-05-21 17:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClergicalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('pastoral_role', models.CharField(max_length=20, verbose_name='rôle pastoral')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('revoked', 'Révoquée'), ('expired', 'Expirée')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_clergy_invitations', to=settings.AUTH_USER_MODEL, verbose_name='accepté par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_clergy_invitations', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clergy_invitations', to='org.diocese', verbose_name='diocèse')),
            ],
            options={
                'verbose_name': 'invitation clergé',
                'verbose_name_plural': 'invitations clergé',
                'ordering': ['-created_at'],
            },
        ),
    ]
