# Generated by Django 5.2.7 on 2026-05-31 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_accounts', '0001_initial'),
        ('org', '0003_backfill_main_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergicalinvitation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clergy_invitations', to='org.church', verbose_name='église cible'),
        ),
        migrations.AddField(
            model_name='clergicalinvitation',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clergy_invitations', to='org.parish', verbose_name='paroisse cible'),
        ),
    ]
