# Generated by Django 5.2.7 on 2026-06-25 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0003_backfill_main_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved_by_origin', "Approuvée par la paroisse d'origine"), ('acknowledged_by_destination', 'Accusée par la paroisse de destination'), ('completed', 'Finalisée'), ('rejected', 'Rejetée')], db_index=True, default='pending', max_length=30, verbose_name='statut')),
                ('reason', models.TextField(blank=True, default='', verbose_name='motif')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='motif de rejet')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='org.parish', verbose_name='paroisse de destination')),
                ('origin_parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='org.parish', verbose_name="paroisse d'origine")),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
            ],
            options={
                'verbose_name': 'demande de transfert paroissial',
                'verbose_name_plural': 'demandes de transfert paroissial',
                'ordering': ['-created_at'],
            },
        ),
    ]
