# Generated by Django 5.2.7 on 2026-04-29 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('baptism', 'Certificat de baptême'), ('first_communion', 'Attestation de première communion'), ('confirmation', 'Attestation de confirmation'), ('religious_marriage', 'Attestation de mariage religieux'), ('godparent', 'Attestation parrain / marraine')], db_index=True, max_length=30)),
                ('reason', models.CharField(choices=[('religious_marriage', 'Mariage religieux'), ('godparent', 'Parrain / marraine'), ('catechism', 'Inscription catéchèse'), ('parish_file', 'Dossier paroissial'), ('personal', 'Usage personnel'), ('other', 'Autre')], max_length=30)),
                ('reason_free', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('under_verification', 'En vérification'), ('info_requested', 'Complément demandé'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('document_deposited', 'Document déposé')], db_index=True, default='submitted', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('requester_last_name', models.CharField(max_length=100)),
                ('requester_first_names', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254)),
                ('registered_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('registered_first_names', models.CharField(blank=True, default='', max_length=200)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('parish_name', models.CharField(max_length=200)),
                ('diocese', models.CharField(max_length=200)),
                ('sacrament_approximate_date', models.CharField(max_length=20)),
                ('sacrament_location', models.CharField(max_length=200)),
                ('additional_info', models.TextField(blank=True, default='')),
                ('document_details', models.JSONField(blank=True, default=dict)),
                ('consent_given', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_document_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de document',
                'verbose_name_plural': 'Demandes de documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('user_supporting', 'Justificatif fidèle'), ('parish_final', 'Document final paroisse')], default='user_supporting', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_request_attachments', to='files.file')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.documentrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='documents.documentrequest')),
            ],
            options={
                'verbose_name': 'Journal de statut',
                'verbose_name_plural': 'Journaux de statut',
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_internal_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='documents.documentrequest')),
            ],
            options={
                'verbose_name': 'Note interne',
                'verbose_name_plural': 'Notes internes',
            },
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['requester', '-created_at'], name='docreq_requester_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['status', '-created_at'], name='docreq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['document_type', 'status'], name='docreq_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequeststatuslog',
            index=models.Index(fields=['request', 'created_at'], name='doclog_request_idx'),
        ),
    ]
