# Generated by Django 5.2.7 on 2026-05-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('org', '0003_backfill_main_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='target_parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='org.parish'),
        ),
    ]
