# Generated by Django 5.2.7 on 2026-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_clergy_only',
            field=models.BooleanField(default=False),
        ),
    ]
