# Generated by Django 5.2.7 on 2026-04-29 08:52

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='adresse email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='numéro de téléphone')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('province_admin', 'Admin Province'), ('diocese_admin', 'Admin Diocèse'), ('parish_admin', 'Admin Paroisse'), ('church_admin', 'Admin Église'), ('fidele', 'Fidèle')], db_index=True, max_length=20, verbose_name='rôle')),
                ('is_verified', models.BooleanField(default=False, help_text="L'utilisateur a validé son adresse email.", verbose_name='email vérifié')),
                ('is_active', models.BooleanField(default=False, help_text='Désactivez plutôt que de supprimer le compte.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Accès à l'interface d'administration Django.", verbose_name='membre du staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrateur')),
                ('jwt_key', models.UUIDField(default=uuid.uuid4, help_text='Rotation invalide tous les tokens JWT actifs.')),
                ('groups', models.ManyToManyField(blank=True, related_name='baseuser_set', to='auth.group', verbose_name='groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='baseuser_permissions_set', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='nom')),
                ('title', models.CharField(blank=True, choices=[('MR', 'M.'), ('MRS', 'Mme')], default='', max_length=10, verbose_name='civilité')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('primary_parish', models.IntegerField(blank=True, null=True, verbose_name='paroisse principale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('REGISTER', 'Inscription'), ('EMAIL_VERIFIED', 'Email vérifié'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PWD_RESET_REQUEST', 'Demande réinitialisation MDP'), ('PWD_RESET_CONFIRM', 'Réinitialisation MDP confirmée'), ('PWD_CHANGED', 'Mot de passe modifié'), ('EMAIL_CHANGE_REQUEST', 'Demande changement email'), ('EMAIL_CHANGE_CONFIRM', 'Changement email confirmé'), ('EMAIL_CHANGE_REVERTED', 'Changement email annulé'), ('ACCOUNT_ACTIVATED', 'Compte activé'), ('ACCOUNT_DEACTIVATED', 'Compte désactivé'), ('ACCOUNT_SOFT_DELETED', 'Compte supprimé (soft)'), ('ACCOUNT_HARD_DELETED', 'Compte supprimé (définitif)'), ('ADMIN_CREATED', 'Compte créé par admin'), ('PROFILE_UPDATED', 'Profil mis à jour')], db_index=True, max_length=50, verbose_name='événement')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IPv4 ou IPv6 nettoyée par le reverse proxy.', null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données contextuelles non sensibles (ex: nouvelle email masquée).', verbose_name='métadonnées')),
                ('user', models.ForeignKey(blank=True, help_text="NULL si l'utilisateur a été supprimé définitivement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'journal de sécurité',
                'verbose_name_plural': 'journaux de sécurité',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event'], name='users_secur_user_id_498ab5_idx'), models.Index(fields=['event', 'created_at'], name='users_secur_event_e050a2_idx')],
            },
        ),
    ]
