# Generated by Django 5.2.7 on 2026-05-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org.diocese', verbose_name='diocèse'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='followed_parishes',
            field=models.ManyToManyField(blank=True, related_name='followers', to='org.parish', verbose_name='paroisses suivies'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='onboarding_state',
            field=models.CharField(choices=[('pending_email', 'Email à vérifier'), ('pending_parish', 'Paroisse à sélectionner'), ('completed', 'Complété')], db_index=True, default='pending_email', max_length=30, verbose_name='état onboarding'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='pastoral_role',
            field=models.CharField(blank=True, choices=[('fidele', 'Fidèle'), ('religieux', 'Religieux/Religieuse'), ('diacre', 'Diacre'), ('pretre', 'Prêtre'), ('eveque', 'Évêque'), ('archeveque', 'Archevêque')], db_index=True, max_length=20, null=True, verbose_name='rôle pastoral'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org.province', verbose_name='province'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='religious_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org.religiouscommunity', verbose_name='communauté religieuse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='org.parish', verbose_name='paroisse principale'),
        ),
    ]
