# Generated by Django 5.2.7 on 2026-05-31 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_deanery_parish_deanery_church'),
        ('users', '0002_add_pastoral_territorial_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('province_admin', 'Admin Province'), ('diocese_admin', 'Admin Diocèse'), ('parish_admin', 'Admin Paroisse'), ('church_admin', 'Admin Église'), ('fidele', 'Fidèle')], db_index=True, max_length=20, verbose_name='rôle / capacité')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('province', 'Province'), ('diocese', 'Diocèse'), ('parish', 'Paroisse'), ('church', 'Église')], db_index=True, max_length=20, verbose_name='niveau de portée')),
                ('is_principal', models.BooleanField(default=False, help_text="Curé principal de la paroisse / responsable principal de l'église.", verbose_name='titulaire principal')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='note')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='org.church', verbose_name='église')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='org.diocese', verbose_name='diocèse')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='attribuée par')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='org.parish', verbose_name='paroisse')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='org.province', verbose_name='province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'affectation de rôle',
                'verbose_name_plural': 'affectations de rôle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_rolea_user_id_e6799d_idx'), models.Index(fields=['role', 'scope'], name='users_rolea_role_52874b_idx'), models.Index(fields=['parish', 'is_active'], name='users_rolea_parish__16bfb7_idx'), models.Index(fields=['diocese', 'is_active'], name='users_rolea_diocese_2beb9b_idx'), models.Index(fields=['church', 'is_active'], name='users_rolea_church__7471ab_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_principal', True), ('scope', 'parish')), fields=('parish',), name='unique_active_principal_per_parish')],
            },
        ),
    ]
