# Generated by Django 5.2.7 on 2026-06-01 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_backfill_main_church'),
        ('users', '0005_backfill_onboarding_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Église de référence : pilote diocèse/province et primary_parish.', verbose_name='appartenance principale')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='org.church', verbose_name='église')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appartenance',
                'verbose_name_plural': 'appartenances',
                'ordering': ['-is_primary', 'created_at'],
                'indexes': [models.Index(fields=['user', 'is_primary'], name='users_membe_user_id_448c53_idx'), models.Index(fields=['church'], name='users_membe_church__f9896d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'church'), name='unique_membership_user_church'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_membership_per_user')],
            },
        ),
    ]
