# Generated by Django 5.2.7 on 2026-06-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_backfill_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='followed_parishes',
        ),
    ]
