# Generated by Django 5.2.7 on 2026-07-19 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('org', '0003_backfill_main_church'),
        ('users', '0009_clergy_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='event',
            field=models.CharField(choices=[('REGISTER', 'Inscription'), ('EMAIL_VERIFIED', 'Email vérifié'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PWD_RESET_REQUEST', 'Demande réinitialisation MDP'), ('PWD_RESET_CONFIRM', 'Réinitialisation MDP confirmée'), ('PWD_CHANGED', 'Mot de passe modifié'), ('EMAIL_CHANGE_REQUEST', 'Demande changement email'), ('EMAIL_CHANGE_CONFIRM', 'Changement email confirmé'), ('EMAIL_CHANGE_REVERTED', 'Changement email annulé'), ('ACCOUNT_ACTIVATED', 'Compte activé'), ('ACCOUNT_DEACTIVATED', 'Compte désactivé'), ('ACCOUNT_SOFT_DELETED', 'Compte supprimé (soft)'), ('ACCOUNT_HARD_DELETED', 'Compte supprimé (définitif)'), ('ADMIN_CREATED', 'Compte créé par admin'), ('PROFILE_UPDATED', 'Profil mis à jour'), ('CLERGY_DECLARED', 'Auto-déclaration clergé déposée'), ('CLERGY_APPROVED', 'Compte clergé validé'), ('CLERGY_REJECTED', 'Compte clergé refusé')], db_index=True, max_length=50, verbose_name='événement'),
        ),
        migrations.CreateModel(
            name='ClergySelfDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_pastoral_role', models.CharField(choices=[('fidele', 'Fidèle'), ('religieux', 'Religieux/Religieuse'), ('diacre', 'Diacre'), ('pretre', 'Prêtre'), ('eveque', 'Évêque'), ('archeveque', 'Archevêque')], db_index=True, help_text="Revendication SANS effet tant qu'elle n'est pas approuvée.", max_length=20, verbose_name='rôle pastoral revendiqué')),
                ('message', models.TextField(blank=True, default='', help_text="Précisions facultatives adressées à l'autorité validante.", verbose_name='message du demandeur')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de décision')),
                ('rejection_reason', models.CharField(blank=True, default='', help_text='Restitué au demandeur : il doit pouvoir corriger et resoumettre.', max_length=500, verbose_name='motif du refus')),
                ('justification_file', models.ForeignKey(help_text="Pièce justificative — un fichier n'est valide qu'une fois téléversé.", on_delete=django.db.models.deletion.PROTECT, related_name='clergy_declarations', to='files.file', verbose_name='justificatif')),
                ('parish', models.ForeignKey(help_text="Territoire revendiqué : détermine l'autorité compétente.", on_delete=django.db.models.deletion.PROTECT, related_name='clergy_declarations', to='org.parish', verbose_name='paroisse de rattachement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clergy_declarations', to=settings.AUTH_USER_MODEL, verbose_name='tranchée par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clergy_declarations', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
            ],
            options={
                'verbose_name': 'auto-déclaration de clergé',
                'verbose_name_plural': 'auto-déclarations de clergé',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_clerg_status_0a6367_idx'), models.Index(fields=['user', 'status'], name='users_clerg_user_id_f74bfc_idx'), models.Index(fields=['parish', 'status'], name='users_clerg_parish__b9f5dc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_clergy_declaration_per_user')],
            },
        ),
    ]
