# Generated by Django 5.2.7 on 2026-05-21 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'diocèse',
                'verbose_name_plural': 'diocèses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('country', models.CharField(default='Senegal', max_length=100, verbose_name='pays')),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReligiousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='abréviation')),
            ],
            options={
                'verbose_name': 'ordre religieux',
                'verbose_name_plural': 'ordres religieux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ville')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='org.diocese', verbose_name='diocèse')),
            ],
            options={
                'verbose_name': 'paroisse',
                'verbose_name_plural': 'paroisses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='diocese',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dioceses', to='org.province', verbose_name='province'),
        ),
        migrations.CreateModel(
            name='ReligiousCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='org.diocese', verbose_name='diocèse')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='org.parish', verbose_name='paroisse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='org.religiousorder', verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'communauté religieuse',
                'verbose_name_plural': 'communautés religieuses',
                'ordering': ['name'],
            },
        ),
    ]
