# Generated by Django 5.2.7 on 2026-05-31 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_deaneries', to=settings.AUTH_USER_MODEL, verbose_name='doyen')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deaneries', to='org.diocese', verbose_name='diocèse')),
            ],
            options={
                'verbose_name': 'doyenné',
                'verbose_name_plural': 'doyennés',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='parish',
            name='deanery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='org.deanery', verbose_name='doyenné'),
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('church_type', models.CharField(choices=[('paroissiale', 'Église paroissiale'), ('succursale', 'Succursale'), ('chapelle', 'Chapelle'), ('station', 'Station / Mission')], db_index=True, default='paroissiale', max_length=20, verbose_name="type d'église")),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text="L'église paroissiale principale. Une seule par paroisse.", verbose_name='église principale')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churches', to='org.parish', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'église',
                'verbose_name_plural': 'églises',
                'ordering': ['parish__name', '-is_main', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('parish',), name='unique_main_church_per_parish')],
            },
        ),
    ]
