# Generated by Django 5.2.7 on 2026-06-05 21:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0003_backfill_main_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralReflection',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reflection_date', models.DateField(db_index=True, verbose_name='Date de la réflexion')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('scope_type', models.CharField(choices=[('global', "Global (toute l'Église du Sénégal)"), ('diocese', 'Diocèse'), ('parish', 'Paroisse'), ('church', 'Église')], db_index=True, default='parish', max_length=20, verbose_name='Portée')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_reflections', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('scope_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_reflections', to='org.church', verbose_name='Église')),
                ('scope_diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_reflections', to='org.diocese', verbose_name='Diocèse')),
                ('scope_parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_reflections', to='org.parish', verbose_name='Paroisse')),
            ],
            options={
                'verbose_name': 'Réflexion pastorale',
                'verbose_name_plural': 'Réflexions pastorales',
                'ordering': ['-reflection_date', '-created_at'],
                'indexes': [models.Index(fields=['reflection_date', 'scope_type'], name='idx_reflection_date_scope')],
                'unique_together': {('author', 'reflection_date')},
            },
        ),
    ]
