# Generated by Django 5.2.7 on 2026-05-21 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRosary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intention', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='active', max_length=20)),
                ('current_decade', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_rosaries', to=settings.AUTH_USER_MODEL)),
                ('mystery_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_sessions', to='rosary.mysterygroup')),
            ],
            options={
                'verbose_name': 'Chapelet communautaire',
                'verbose_name_plural': 'Chapelets communautaires',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RosaryIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('rosary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to='rosary.communityrosary')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_rosary_intentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intention chapelet',
                'verbose_name_plural': 'Intentions chapelet',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RosaryParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rosary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rosary.communityrosary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosary_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant chapelet',
                'verbose_name_plural': 'Participants chapelet',
                'unique_together': {('rosary', 'user')},
            },
        ),
    ]
