# Generated by Django 5.2.7 on 2026-05-21 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('event_type', models.CharField(choices=[('mass', 'Messe'), ('conference', 'Conférence'), ('retreat', 'Retraite'), ('ordination', 'Ordination'), ('other', 'Autre')], db_index=True, default='other', max_length=20, verbose_name='type')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='début')),
                ('end_at', models.DateTimeField(verbose_name='fin')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='lieu')),
                ('scope_type', models.CharField(choices=[('global', 'Mondial'), ('province', 'Province'), ('diocese', 'Diocèse'), ('parish', 'Paroisse')], db_index=True, default='global', max_length=20, verbose_name='portée')),
                ('scope_id', models.IntegerField(blank=True, null=True, verbose_name='ID territoire')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='agenda.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription événement',
                'verbose_name_plural': 'Inscriptions événements',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at', 'scope_type'], name='event_start_scope_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
    ]
