# Generated by Django 5.2.7 on 2026-07-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_event_scope_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='annulé le'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_events', to=settings.AUTH_USER_MODEL, verbose_name='annulé par'),
        ),
    ]
